// Constants describing the Secure Storage keys
export const STORAGE_KEYS = {
    AUTH_TOKEN: 'AUTH_TOKEN',
    EXPIRES_AT: 'EXPIRES_AT',
    HAS_APP_BEEN_USED: 'HAS_APP_BEEN_USED',
    IS_FIRST_USE: 'IS_FIRST_USE',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    USER_DATA: 'USER_DATA',
    // streak + rewards
    STREAK_COUNT: 'STREAK_COUNT',
    LAST_OPEN_DATE: 'LAST_OPEN_DATE',
    COIN_BALANCE: 'COIN_BALANCE',
    TASKS: 'TASKS',
    HAS_SEEN_WELCOME: 'HAS_SEEN_WELCOME'
};
